"""empty message

Revision ID: 07293072f23a
Revises: 83c20aac03eb
Create Date: 2025-04-29 04:00:05.743949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07293072f23a'
down_revision = '83c20aac03eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using='price::double precision')
        batch_op.drop_constraint('dishes_price_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.create_unique_constraint('dishes_price_key', ['price'])
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
