"""empty message

Revision ID: 1ee5127dd15c
Revises: f96a3b24d5f6
Create Date: 2025-04-26 01:25:32.149495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ee5127dd15c'
down_revision = 'f96a3b24d5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'cliente', 'mesero', 'cocina', name='user_role_enum'),
               type_=sa.Enum('ADMIN', 'CLIENTE', 'MESERO', 'COCINA', name='user_role_enum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'CLIENTE', 'MESERO', 'COCINA', name='user_role_enum', native_enum=False),
               type_=postgresql.ENUM('admin', 'cliente', 'mesero', 'cocina', name='user_role_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###
